# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Storyboard Script Library
email: me@enkrypton.moe
description: >- # this means to ignore newlines until "baseurl:"
  Storyboard Script Library
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
analytics-id:
# Social settings
github: Enkrypton/osb
maintainers:
  - Enkrypton

# Build settings
plugins:
  - jekyll-assets
  - kramdown
  - uglifier
  - jekyll-include-cache

# source: src
# destination: www
markdown: kramdown

cards:
  data: scripts         # yaml file in _data (without .yml)
  comments: false
  group_by:
    name: type      # field in yaml to group by
    caption: type  # name of category (ex: industries)
    fa-icon: folder-open
    fa-style: far        # valid: fas (solid), far (regular), fal (light), fab (brand)
  meta:               # use this section to display card info, in addition to 'group_by'
    - name: usage
      caption: usage
      fa-icon: code
      fa-style: far


compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier

include:
  - CNAME
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
